#!/bin/bash

set -e

if [ ! -x "$(command -v golangci-lint)" ]; then
    go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
fi


golangci-lint run --tests --disable-all --deadline=600s \
    --enable=misspell \
    --enable=vet \
    --enable=ineffassign \
    --enable=gofmt \
    --enable=gocyclo \
    --enable=golint \
    ./...
